//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public string username { get; set; }
        public string hash { get; set; }
        public Nullable<bool> banned { get; set; }
        public string Email { get; set; }
        public Nullable<bool> EmailVal { get; set; }
        public System.DateTime registeredTime { get; set; }
        public System.DateTime lastLoggin { get; set; }
        public int playTime { get; set; }
    }
}
