// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Server.Database;
using System;

namespace Server.Migrations
{
    [DbContext(typeof(UserDatabase))]
    [Migration("20180506152712_initialCreate")]
    partial class initialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011");

            modelBuilder.Entity("Server.Database.Ban", b =>
                {
                    b.Property<uint>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ip");

                    b.Property<string>("mac");

                    b.Property<string>("reason");

                    b.Property<uint?>("userId");

                    b.HasKey("id");

                    b.HasIndex("userId");

                    b.ToTable("bans");
                });

            modelBuilder.Entity("Server.Database.Clan", b =>
                {
                    b.Property<uint>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("name");

                    b.Property<string>("tag");

                    b.HasKey("id");

                    b.ToTable("clans");
                });

            modelBuilder.Entity("Server.Database.Login", b =>
                {
                    b.Property<uint>("userId");

                    b.Property<int>("ip");

                    b.Property<string>("mac");

                    b.HasKey("userId");

                    b.ToTable("logins");
                });

            modelBuilder.Entity("Server.Database.User", b =>
                {
                    b.Property<uint>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.Property<uint?>("clanId");

                    b.Property<string>("email")
                        .IsRequired();

                    b.Property<string>("name")
                        .IsRequired();

                    b.Property<byte>("permission");

                    b.HasKey("id");

                    b.HasIndex("clanId");

                    b.ToTable("users");
                });

            modelBuilder.Entity("Server.Database.Ban", b =>
                {
                    b.HasOne("Server.Database.User", "user")
                        .WithMany("bans")
                        .HasForeignKey("userId");
                });

            modelBuilder.Entity("Server.Database.Login", b =>
                {
                    b.HasOne("Server.Database.User", "user")
                        .WithOne("login")
                        .HasForeignKey("Server.Database.Login", "userId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Server.Database.User", b =>
                {
                    b.HasOne("Server.Database.Clan", "clan")
                        .WithMany("members")
                        .HasForeignKey("clanId");
                });
#pragma warning restore 612, 618
        }
    }
}
