// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Server.Database;
using System;

namespace Server.Migrations
{
    [DbContext(typeof(ArenaDatabase))]
    [Migration("arena_initialCreate")]
    partial class initialArenaCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011");
         
            modelBuilder.Entity("Server.Database.Arena", b =>
            {
                b.Property<uint>("Id")
                    .ValueGeneratedOnAdd();

                b.Property<uint>("ArenaId");

                b.Property<string>("Name")
                    .IsRequired();

                b.Property<long>("X");

                b.Property<long>("Y");

                b.Property<long>("Z");

                b.HasKey("Id");

                b.ToTable("Arenas");
            });        
#pragma warning restore 612, 618
        }
    }
}
